### ISSUE TITLE
No plugin was found for the platform "HomeBridgeSmartThings" in your config.json

### ISSUE THREAD

**Issue by danielpoon** [iklein99/homebridge-smartthings#11]
**Describe The Bug:**
No plugin was found for the platform "HomeBridgeSmartThings" in your config.json. Please make sure the corresponding plugin is installed correctly.

**To Reproduce:**
Restart homebridge and watch the log

I installed Homebridge using this:
sudo apt-get install homebridge

I installed the plugin using this:
sudo su
sudo hb-shell
npm -v
npm i https://github.com/iklein99/homebridge-smartthings

**Expected behavior:**
To automatically detect Smarttthings devices/accessory

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```
[8/4/2022, 3:55:41 PM] ====================
[8/4/2022, 3:55:41 PM] ERROR LOADING PLUGIN homebridge-smartthings-ik:
[8/4/2022, 3:55:41 PM] Error: Cannot find module '/var/lib/homebridge/node_modules/homebridge-smartthings-ik/dist/index.js'
Require stack:
- /var/lib/homebridge/node_modules/homebridge/lib/plugin.js
- /var/lib/homebridge/node_modules/homebridge/lib/pluginManager.js
- /var/lib/homebridge/node_modules/homebridge/lib/server.js
- /var/lib/homebridge/node_modules/homebridge/lib/cli.js
- /var/lib/homebridge/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Plugin.load (/var/lib/homebridge/node_modules/homebridge/src/plugin.ts:227:93)
    at PluginManager.initializeInstalledPlugins (/var/lib/homebridge/node_modules/homebridge/src/pluginManager.ts:141:22)
    at Server.start (/var/lib/homebridge/node_modules/homebridge/src/server.ts:173:30)
[8/4/2022, 3:55:41 PM] ====================
[8/4/2022, 3:55:41 PM] No plugin was found for the platform "HomeBridgeSmartThings" in your config.json. Please make sure the corresponding plugin is installed correctly.
[8/4/2022, 3:55:41 PM] Loading 2 platforms...
Setup Payload:
X-HM://0024L67EXKT30
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                                             
[8/4/2022, 3:55:41 PM] Homebridge v1.5.0 (HAP v0.10.2) (Homebridge 90C2) is running on port 51800.
[8/4/2022, 4:04:21 PM] [Homebridge UI] Homebridge restart request received
[8/4/2022, 4:04:21 PM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[8/4/2022, 4:04:21 PM] [Homebridge UI] Sending SIGTERM to Homebridge
[8/4/2022, 4:04:21 PM] Got SIGTERM, shutting down Homebridge...
[8/4/2022, 4:04:26 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[8/4/2022, 4:04:31 PM] [HB Supervisor] Restarting Homebridge...
[8/4/2022, 4:04:31 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[8/4/2022, 4:04:31 PM] [HB Supervisor] Started Homebridge v1.5.0 with PID: 3735
[8/4/2022, 4:04:31 PM] Loaded config.json with 0 accessories and 2 platforms.
[8/4/2022, 4:04:31 PM] Loaded 0 cached accessories from cachedAccessories.
[8/4/2022, 4:04:31 PM] ---
[8/4/2022, 4:04:31 PM] ====================
[8/4/2022, 4:04:31 PM] ERROR LOADING PLUGIN homebridge-smartthings-ik:
[8/4/2022, 4:04:31 PM] Error: Cannot find module '/var/lib/homebridge/node_modules/homebridge-smartthings-ik/dist/index.js'
Require stack:
- /var/lib/homebridge/node_modules/homebridge/lib/plugin.js
- /var/lib/homebridge/node_modules/homebridge/lib/pluginManager.js
- /var/lib/homebridge/node_modules/homebridge/lib/server.js
- /var/lib/homebridge/node_modules/homebridge/lib/cli.js
- /var/lib/homebridge/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Plugin.load (/var/lib/homebridge/node_modules/homebridge/src/plugin.ts:227:93)
    at PluginManager.initializeInstalledPlugins (/var/lib/homebridge/node_modules/homebridge/src/pluginManager.ts:141:22)
    at Server.start (/var/lib/homebridge/node_modules/homebridge/src/server.ts:173:30)
[8/4/2022, 4:04:31 PM] ====================
[8/4/2022, 4:04:31 PM] No plugin was found for the platform "HomeBridgeSmartThings" in your config.json. Please make sure the corresponding plugin is installed correctly.
[8/4/2022, 4:04:31 PM] Loading 2 platforms...
Setup Payload:
X-HM://0024L67EXKT30

**Plugin Config:**

```json
{
    "name": "Smartthings Plug (IK)",
    "BaseURL": "https://api.smartthings.com/v1/",
    "AccessToken": "xxx",
    "GarageDoorMaxPoll": 40,
    "platform": "HomeBridgeSmartThings"
}```

**Screenshots:**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment:**

* **Plugin Version**: homebridge-smartthings-ik v1.1.7-beta.6
* **Homebridge Version**: v1.5.0
* **Node.js Version**: v1.5.0
* **NPM Version**: v1.5.0
* **Operating System**: Ubuntu 22.04 LTS

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by danielpoon** [comment]
Got it reinstalled via the Homebridge UI and worked. Not sure why doing it in terminal doesn't. It's good enough for me.

**Comment by iklein99** [comment]
Sorry I was away.  I see that you have it working.  That is they way I would recommend installing it.  Thanks.
