### ISSUE TITLE
Polling failure on lock ends child bridge process

### ISSUE THREAD

**Issue by jjeaton** [iklein99/homebridge-smartthings#211]
**Describe The Bug:**

Locking my door from HomeKit will lock the door, but the polling never updates the lock status. Checking the logs, the child bridge process is quit and restarted automatically after the failure. The lock then switches to "No Response" in Homekit. The only way for me to get my lock to update again, is to edit its settings in the Home app, which causes it to poll again.

**To Reproduce:**

* Update to latest homebridge and version of this plugin.
* Lock the door
* See the lock status never change, and eventually move to "No Response"

**Expected behavior:**

I expect the door to lock and the status to update in the Homekit app

**Logs:**

```
[8/29/2023, 4:38:47 PM] [homebridge-smartthings-ik] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[8/29/2023, 4:39:00 PM] [homebridge-smartthings-ik] This plugin slows down Homebridge. The read handler for the characteristic 'Lock Current State' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[8/29/2023, 4:39:00 PM] [homebridge-smartthings-ik] This plugin slows down Homebridge. The read handler for the characteristic 'Lock Target State' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[8/29/2023, 4:39:00 PM] [homebridge-smartthings-ik] This plugin slows down Homebridge. The read handler for the characteristic 'Status Low Battery' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[8/29/2023, 4:39:00 PM] [homebridge-smartthings-ik] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[8/29/2023, 4:39:06 PM] [homebridge-smartthings-ik] This plugin slows down Homebridge. The read handler for the characteristic 'Lock Current State' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[8/29/2023, 4:39:06 PM] [homebridge-smartthings-ik] This plugin slows down Homebridge. The read handler for the characteristic 'Lock Target State' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[8/29/2023, 4:39:06 PM] [homebridge-smartthings-ik] This plugin slows down Homebridge. The read handler for the characteristic 'Status Low Battery' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[8/29/2023, 4:39:06 PM] [homebridge-smartthings-ik] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[8/29/2023, 4:39:35 PM] [Smartthings Plug (IK)] Failed to request status from Front Door Lock: Error: connect ETIMEDOUT 3.134.23.99:443.  This is failure number 1
[8/29/2023, 4:39:35 PM] [Smartthings Plug (IK)] Poll failure on Front Door Lock
[8/29/2023, 4:39:35 PM] [Smartthings Plug (IK)] Poll failure on Front Door Lock
Error: HAP Status Error: -70402
    at new HapStatusError (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/hapStatusError.ts:17:5)
    at /volume1/homebridge/node_modules/homebridge-smartthings-ik/src/services/lockService.ts:58:20
[8/29/2023, 4:39:35 PM] [Smartthings Plug (IK)] Child bridge process ended
[8/29/2023, 4:39:35 PM] [Smartthings Plug (IK)] Process Ended. Code: 1, Signal: null
[8/29/2023, 4:39:42 PM] [Smartthings Plug (IK)] Restarting Process...
[8/29/2023, 4:39:43 PM] [Smartthings Plug (IK)] Launched child bridge with PID 8817
[8/29/2023, 4:39:43 PM] Registering platform 'homebridge-smartthings-ik.HomeBridgeSmartThings'
[8/29/2023, 4:39:43 PM] [Smartthings Plug (IK)] Loaded homebridge-smartthings-ik v1.5.14 child bridge successfully
[8/29/2023, 4:39:43 PM] Loaded 2 cached accessories from cachedAccessories.
[8/29/2023, 4:39:43 PM] [Smartthings Plug (IK)] Loading accessory from cache: Front Door Switch
[8/29/2023, 4:39:43 PM] [Smartthings Plug (IK)] Loading accessory from cache: Front Door Lock
[8/29/2023, 4:39:43 PM] Homebridge v1.6.1 (HAP v0.11.1) (Smartthings Plug (IK)) is running on port 50864.
[8/29/2023, 4:39:43 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Front Door Switch
[8/29/2023, 4:39:44 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Front Door Lock

```

**Plugin Config:**

```json
 {
            "name": "Smartthings Plug (IK)",
            "BaseURL": "https://api.smartthings.com/v1/",
            "AccessToken": "",
            "GarageDoorMaxPoll": 40,
            "PollLocksSeconds": 10,
            "PollDoorsSeconds": 10,
            "PollSensorsSeconds": 5,
            "PollSwitchesAndLightsSeconds": 10,
            "IgnoreDevices": [
            ],
            "_bridge": {
                "username": "MAC ADDRESS",
                "port": 50864
            },
            "platform": "HomeBridgeSmartThings"
        },
```

**Screenshots:**

**Environment:**

* **Plugin Version**: v1.5.14
* **Homebridge Version**:  v1.6.1
* **Node.js Version**:  v18.15.0
* **NPM Version**:  v9.6.7
* **Operating System**:  hb-service Synology

**Comment by iklein99** [comment]
Please follow the directions in the linked document and send me the detailed logs after reproducing the error.  Please remember to truncate the logs first.
[Instructions for Producing a Detailed Log.pdf](https://github.com/iklein99/homebridge-smartthings/files/12837865/Instructions.for.Producing.a.Detailed.Log.pdf)
