### ISSUE TITLE
HomeBridge cycling up and down after sensor added 

### ISSUE THREAD

**Issue by philmehew** [iklein99/homebridge-smartthings#33]
The SmartThings child bridge is now constantly cycling up and down v.131 and v.132.

I think this has started happening since I re-attached a Fibaro Motion Sensor to SmartThings:

[9/29/2022, 4:44:07 PM] [Smartthings Plug (IK)] Restarting Process...
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Launched child bridge with PID 31472
[9/29/2022, 4:44:08 PM] Registering platform 'homebridge-smartthings-ik.HomeBridgeSmartThings'
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loaded homebridge-smartthings-ik v1.3.2 child bridge successfully
[9/29/2022, 4:44:08 PM] Loaded 27 cached accessories from cachedAccessories.0EEFD6C88382.
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Lounge Corner
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Landing Plug
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Conservatory Dimmer
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Downstairs Loo Light
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Fire Alarm Plug
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Lounge Temp Virtual Switch
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Cinema Room Spotlight
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Conservatory 2
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Lounge Window
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: If Smoke Alarms Activated
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Conservatory 3
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Office Light
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Bedroom Fan
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Porch Light
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Office Lamp
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Conservatory 5
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Lounge Plug 2
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Conservatory 6
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Fire Alarm Virtual Lock
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Conservatory 1
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Bedroom Light
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Office Plug
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Lounge Plug
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Conservatory 4
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Bedroom Motion Sensor
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Fibaro Motion Sensor
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Loading accessory from cache: Loo Motion Sensor
[9/29/2022, 4:44:08 PM] Homebridge v1.5.0 (HAP v0.10.2) (Smartthings Plug (IK)) is running on port 50726.
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Lounge Corner
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Landing Plug
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Conservatory Dimmer
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Bedroom Motion Sensor
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Fibaro Motion Sensor
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Downstairs Loo Light
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Fire Alarm Plug
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Lounge Temp Virtual Switch
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Cinema Room Spotlight
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Loo Motion Sensor
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Conservatory 2
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Lounge Window
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: If Smoke Alarms Activated
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Conservatory 3
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Office Light
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Bedroom Fan
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Porch Light
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Office Lamp
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Conservatory 5
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Lounge Plug 2
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Conservatory 6
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Fire Alarm Virtual Lock
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Conservatory 1
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Bedroom Light
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Office Plug
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Lounge Plug
[9/29/2022, 4:44:08 PM] [Smartthings Plug (IK)] Restoring existing accessory from cache: Conservatory 4
[9/29/2022, 4:44:09 PM] [Smartthings Plug (IK)] Conservatory Dimmer is offline
[9/29/2022, 4:44:09 PM] [Smartthings Plug (IK)] Conservatory Dimmeris offline
[9/29/2022, 4:44:09 PM] [Smartthings Plug (IK)] Cinema Room Spotlight is offline
[9/29/2022, 4:44:09 PM] [Smartthings Plug (IK)] Cinema Room Spotlightis offline
[9/29/2022, 4:44:09 PM] [Smartthings Plug (IK)] If Smoke Alarms Activated is offline
[9/29/2022, 4:44:09 PM] [Smartthings Plug (IK)] Office Light is offline
[9/29/2022, 4:44:09 PM] [Smartthings Plug (IK)] Office Lightis offline
[9/29/2022, 4:44:09 PM] [Smartthings Plug (IK)] Office Lamp is offline
[9/29/2022, 4:44:09 PM] [Smartthings Plug (IK)] Office Lampis offline
[9/29/2022, 4:44:09 PM] [Smartthings Plug (IK)] Bedroom Motion Sensor is offline
Error: HAP Status Error: -70402
    at new HapStatusError (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/hapStatusError.ts:15:5)
    at /volume1/homebridge/node_modules/homebridge-smartthings-ik/src/sensorAccessory.ts:139:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[9/29/2022, 4:44:09 PM] [Smartthings Plug (IK)] Child bridge process ended
[9/29/2022, 4:44:09 PM] [Smartthings Plug (IK)] Process Ended. Code: 1, Signal: null

Hope that's helpful, let me know if I can provide any more info.

**Comment by iklein99** [comment]
Your motion sensor is offline.  Add it to the ignore list or remove it from your network.

**Comment by philmehew** [comment]
Thanks, you were correct of course, a motion sensor battery had died.Surely that shouldn’t crash the whole child bridge though, other offline items don’t do that?On 29 Sep 2022, at 18:31, iklein99 ***@***.***> wrote:﻿
Your motion sensor is offline.  Add it to the ignore list or remove it from your network.

**Comment by iklein99** [comment]
I thought I had fixed that problem, but there must be a case here that I missed.  I'll look into it and see.

**Comment by iklein99** [comment]
Fixed this in 1.3.3.

**Comment by philmehew** [comment]
Amazing, thank you, will try and rest.Really appreciate what you’re doing!!!!!On 2 Oct 2022, at 18:03, iklein99 ***@***.***> wrote:﻿
Closed #33 as completed.
