### ISSUE TITLE
Homebridge restart loop when sensor offline

### ISSUE THREAD

**Issue by mjwelch19** [iklein99/homebridge-smartthings#37]
Likely the same as #33 and #30 - only for me it happens to be a door lock offline causing the reboot loop. This happens on `1.3.3` and continues even after downgrading back to `1.2.2` where I was.  The sensor was offline prior to upgrading and HB + ST was still functional - so something in the initial boot/device registration only causing the whole system to fail?

```
[10/3/2022, 8:48:57 AM] [Smartthings Plug (IK)] Front door is offline
[10/3/2022, 8:48:57 AM] Error: HAP Status Error: -70402
    at new HapStatusError (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/hapStatusError.ts:15:5)
    at /var/lib/homebridge/node_modules/homebridge-smartthings-ik/src/lockAccessory.ts:166:23
    at new Promise (<anonymous>)
    at LockPlatformAccessory.getCurrentState (/var/lib/homebridge/node_modules/homebridge-smartthings-ik/src/lockAccessory.ts:162:12)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-smartthings-ik/src/lockAccessory.ts:63:16)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[10/3/2022, 8:48:57 AM] Got SIGTERM, shutting down Homebridge...
[10/3/2022, 8:49:02 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[10/3/2022, 8:49:06 AM] [HB Supervisor] Stopping services...
[10/3/2022, 8:49:07 AM] [HB Supervisor] Restarting Homebridge...
[10/3/2022, 8:49:07 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[10/3/2022, 8:49:07 AM] [HB Supervisor] Started Homebridge v1.5.0 with PID: 17577
```

**Comment by iklein99** [comment]
Same issue.  I fixed it in 1.3.4.
