### ISSUE TITLE
errors after updating plugin

### ISSUE THREAD

**Issue by guylopes71** [iklein99/homebridge-smartthings#67]
I am VERY NEW to this, so please bear with me.

I upgraded the plugin this morning, and these errors have started, and smarting s accessories have stopped responding

Before the upgrade, it all worked fine

example of log
[28/10/2022, 11:28:07] [Smartthings Plug (IK)] Office door is offline
[28/10/2022, 11:28:07] [Smartthings Plug (IK)] Office door is offline
[28/10/2022, 11:28:07] [Smartthings Plug (IK)] Office door is offline
[28/10/2022, 11:28:07] [Smartthings Plug (IK)] Office door is offline
[28/10/2022, 11:28:07] [Smartthings Plug (IK)] garage arriere battery level LOW
[28/10/2022, 11:28:07] Error: HAP Status Error: -70402
    at new HapStatusError (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/hapStatusError.ts:15:5)
    at /var/lib/homebridge/node_modules/homebridge-smartthings-ik/src/services/lockService.ts:55:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[28/10/2022, 11:28:07] Got SIGTERM, shutting down Homebridge...
[28/10/2022, 11:28:12] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[28/10/2022, 11:28:17] [HB Supervisor] Restarting Homebridge...
[28/10/2022, 11:28:17] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[28/10/2022, 11:28:17] [HB Supervisor] Started Homebridge v1.5.1 with PID: 10533
[28/10/2022, 11:28:19] Loaded config.json with 0 accessories and 3 platforms.
[28/10/2022, 11:28:19] Loaded 10 cached accessories from cachedAccessories.
[28/10/2022, 11:28:20] ---
[28/10/2022, 11:28:20] Loaded plugin: homebridge-envisalink@1.2.0
[28/10/2022, 11:28:20] Registering platform 'homebridge-envisalink.Envisalink'
[28/10/2022, 11:28:20] ---
[28/10/2022, 11:28:20] Loaded plugin: homebridge-smartthings-ik@1.4.9
[28/10/2022, 11:28:20] Registering platform 'homebridge-smartthings-ik.HomeBridgeSmartThings'
[28/10/2022, 11:28:20] ---
[28/10/2022, 11:28:20] Loading 3 platforms...
[28/10/2022, 11:28:20] [Envisalink] Initializing Envisalink platform...
[28/10/2022, 11:28:20] [Smartthings Plug (IK)] Initializing HomeBridgeSmartThings platform...
[28/10/2022, 11:28:20] [Smartthings Plug (IK)] Loading accessory from cache: cuisine
[28/10/2022, 11:28:20] [Smartthings Plug (IK)] Loading accessory from cache: Garage Avant
[28/10/2022, 11:28:20] [Smartthings Plug (IK)] Loading accessory from cache: garage arriere
[28/10/2022, 11:28:20] [Smartthings Plug (IK)] Loading accessory from cache: Office door
[28/10/2022, 11:28:20] [Envisalink] Configuring Envisalink platform,  Host: 192.168.2.30 Port: 4025

**Comment by iklein99** [comment]
For now, try putting the Office door in the list of devices to ignore, then find out why it is offline.  That shouldn’t make homebridge shut down - I have to look into that, but doing this may get you up and running again.

**Comment by guylopes71** [comment]
So additional info.
Today I also updated the homebridge software.
I just rolled back your plugin, and at 1.4.7 all is ok, and at 1.4.8 the same error starts to pop.  I brought down to 1.4.7 for now.
Let me know what I can do to help you in this.

**Comment by iklein99** [comment]
Should be fixed in 1.4.10.  Let me know.

**Comment by iklein99** [comment]
Closing
